### ISSUE TITLE
../../libiberty/cplus-dem.c:44:8: erreur: conflicting types for ‘malloc’

### ISSUE THREAD

**Issue by Rudloff** [wikireader/wikireader#33]
I get an error when I try to build on Ubuntu 12.10: https://gist.github.com/4534951
